# Generated by Django 2.2.6 on 2019-11-02 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('find', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fasta',
            old_name='raw_query',
            new_name='accession',
        ),
    ]
