# Generated by Django 2.2.6 on 2019-11-05 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('find', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MicroRNAAlias',
            fields=[
                ('alias', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('accession', models.CharField(max_length=15)),
            ],
        ),
    ]
