# Generated by Django 2.2.6 on 2019-11-06 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('find', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='num_queries',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='user',
            name='num_queries',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
