# Generated by Django 2.2.6 on 2019-11-13 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('find', '0002_auto_20191111_1533'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='query',
            name='most_recent_time_queried',
        ),
    ]
